global:
  scrape_interval:	3s
scrape_configs:
  - job_name: 'graform.api-read-prometheus'
    metrics_path: /metrics
    scheme: http
    static_configs:
     - targets:
        - host.docker.internal:8082      
        
