<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CleanArchitecture.Application\CleanArchitecture.Application.csproj" />
    <ProjectReference Include="..\CleanArchitecture.Infrastructure.Persistence\CleanArchitecture.Infrastructure.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.2" />
    <PackageReference Include="FirebaseAdmin" Version="3.2.0" />
    <PackageReference Include="IPE.SmsIR" Version="1.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Quartz" Version="3.13.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Hubs\" />
    <Folder Include="NewFolder\" />
  </ItemGroup>
</Project>